codecov:
  require_ci_to_pass: true
  status:
    patch: false
  project:
    default:
      target: 95%
      threshold: 2%
      branches:
        - 'master'
  comment:
    layout: 'reach, diff, flags, files'
    behavior: default
    require_changes: false
    branches:
      - 'master'
