language: node_js

node_js:
  - 14

cache:
  directories:
    - 'node_modules'

notifications:
  email:
    on_success: never

branches:
  only:
    - master

install:
  - yarn --frozen-lockfile

script:
  - yarn cli
  - yarn clean
  - yarn
  - yarn hooks
  - yarn icon
  - yarn test
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
